#!/bin/bash
# vim ft: sh

# QJ - quote JSON
# Escapes JSON double quotes, for using with language that uses double quote
# for string
out=$(while read line
do
    echo $line | sed 's/"/\\"/g' | tr '\n' ' '
done < "${1:-/dev/stdin}")
echo \"$out\" | xclip -sel c
echo \"$out\"
