#!/bin/bash
# vim ft: sh

# QJ - quote JSON
# Escapes JSON double quotes, for using with language that uses double quote
# for string
out=$(while read line
do
    echo $line | sed 's/"/\\"/g' | tr '\n' ' '
done < "${1:-/dev/stdin}")
if command -v xclip >/dev/null; then
    echo \"$out\" | xclip -sel c
fi
if command -v pbcopy >/dev/null; then
    echo \"$out\" | pbcopy
fi
echo \"$out\"
